version: "3"
services:
  redis:
    image: redis
    volumes:
      - ./redis-db:/data
    ports:
      - 6379:6379

  nginx:
    image: nginx
    ports:
      - 8080:8080
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
    links:
      - linkshrink

  linkshrink:
    image: linkshrink
    links:
      - redis
    depends_on:
      - redis
    environment:
      - LINKSHRINK_REDIS_HOST=redis
      - LINKSHRINK_LISTEN_HOST=0.0.0.0
